### ISSUE TITLE
Better status when charging while cleaning

### ISSUE THREAD

**Issue by Friedi1970** [trunneml/homeassistant-vorwerk#8]
I figured out a smaller issue.
When VR200 returns back for loading and cleaning is not finished the sensor displays "cleaning". But the VR200 is docked and loading. Don't know whether it is possible to differ this status. I think something like "cleaning/charging" would be not so bad.
![Image](https://user-images.githubusercontent.com/47818803/123216096-76b4af80-d4c9-11eb-966d-48b3a734e250.jpeg)

**Comment by trunneml** [comment]
Home-Assistant just has the states: STATE_ERROR, STATE_RETURNING, STATE_PAUSED, STATE_DOCKED and STATE_CLEANING. (See https://developers.home-assistant.io/docs/core/entity/vacuum/#states)

Vorwerk calls the state: SUSPENDED_CLEANING. I don't like STATE_DOCKED because you don't know if the robot has finished the cleaning or is just charging. STATE_PAUSED means not in dock, so I think STATE_CLEANING is the right one, as the cleaning is still in progress.

**Comment by trunneml** [comment]
I will try to add an attribute to the vacuum entry that shows the orgiginal vorwerk state (SUSPENDED_CLEANING).

**Comment by Friedi1970** [comment]
Sounds good 👌👍
